version: 2.1

jobs:
  api-tests:
    docker:
      - image: cimg/node:current
    steps:
      - run:
          name: Install Newman and Reporter
          command: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra
      
      - run:
          name: Run API Tests
          command: |
            newman run https://api.getpostman.com/collections/d6625051-3a83-4adb-85df-69bc226e0125?access_key=${POSTMAN_API_KEY} \
              --env-var "api_key_value=${CIRCLECI_API_TOKEN}" \
              --reporters cli,htmlextra \
              --reporter-htmlextra-export test-results/api-report.html \
              --reporter-htmlextra-title "CircleCI API Tests"
      
      - store_artifacts:
          path: test-results
          destination: test-reports

workflows:
  test-circleci-api:
    jobs:
      - api-tests:
          context: api-testing-demo