version: 2.1

orbs:
  newman: postman/newman@1.0.0

jobs:
  test-circleci-api:
    executor: newman/postman-newman-docker
    steps:
      - run:
          name: Create Environment File
          command: |
            echo '{
              "values": [
                {
                  "key": "api_key_value",
                  "value": "'${CIRCLECI_API_TOKEN}'",
                  "enabled": true
                }
              ]
            }' > environment.json
      
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/d6625051-3a83-4adb-85df-69bc226e0125?access_key=${POSTMAN_API_KEY}
          environment: environment.json
      
      - store_artifacts:
          path: newman
          destination: test-results

workflows:
  test-api:
    jobs:
      - test-circleci-api:
          context: api-testing-demo