version: 2.1

orbs:
  newman: postman/newman@1.0.0

jobs:
  test-circleci-api:
    executor: newman/postman-newman-docker
    steps:
      # Create environment file
      - run:
          name: Create Environment File
          command: |
            cat > environment.json << EOF
            {
              "values": [
                {
                  "key": "api_key_value",
                  "value": "${CIRCLECI_API_TOKEN}",
                  "enabled": true
                }
              ]
            }
            EOF
      
      # Run Newman with proper parameters
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/d6625051-3a83-4adb-85df-69bc226e0125?access_key=${POSTMAN_API_KEY}
          environment: environment.json
          reporter: htmlextra
          reporter-htmlextra-export: test-results/report.html
      
      - store_artifacts:
          path: test-results
          destination: api-test-reports

workflows:
  test-api:
    jobs:
      - test-circleci-api:
          context: api-testing-demo