version: 2.1

orbs:
  newman: postman/newman@1.0.0

jobs:
  test-circleci-api:
    executor: newman/postman-newman-docker
    steps:
      - run:
          name: Download Collection
          command: |
            # Try to download the public collection
            curl -o collection.json "https://www.getpostman.com/collections/d6625051-3a83-4adb-85df-69bc226e0125"
      
      - run:
          name: Create Environment
          command: |
            echo '{
              "values": [
                {
                  "key": "api_key_value",
                  "value": "'${CIRCLECI_API_TOKEN}'",
                  "enabled": true
                }
              ]
            }' > environment.json
      
      - newman/newman-run:
          collection: collection.json
          environment: environment.json

workflows:
  test-api:
    jobs:
      - test-circleci-api:
          context: api-testing-demo