version: 2.1

orbs:
  newman: postman/newman@1.0.0

jobs:
  test-circleci-api:
    executor: newman/postman-newman-docker
    steps:
      - run:
          name: Create Test Collection
          command: |
            echo '{
              "info": {
                "name": "CircleCI API Demo",
                "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
              },
              "auth": {
                "type": "apikey",
                "apikey": [
                  {"key": "value", "value": "{{api_key_value}}", "type": "string"},
                  {"key": "key", "value": "Circle-Token", "type": "string"},
                  {"key": "in", "value": "header", "type": "string"}
                ]
              },
              "item": [
                {
                  "name": "Get Current User",
                  "request": {
                    "method": "GET",
                    "url": "https://circleci.com/api/v2/me"
                  },
                  "event": [{
                    "listen": "test",
                    "script": {
                      "exec": [
                        "pm.test(\"Status is 200\", () => {",
                        "  pm.response.to.have.status(200);",
                        "});",
                        "pm.test(\"Has user data\", () => {",
                        "  const json = pm.response.json();",
                        "  pm.expect(json).to.have.property(\"login\");",
                        "});"
                      ]
                    }
                  }]
                },
                {
                  "name": "List Projects",
                  "request": {
                    "method": "GET",
                    "url": "https://circleci.com/api/v2/project"
                  },
                  "event": [{
                    "listen": "test",
                    "script": {
                      "exec": [
                        "pm.test(\"Returns projects\", () => {",
                        "  pm.response.to.have.status(200);",
                        "  pm.expect(pm.response.json().items).to.be.an(\"array\");",
                        "});"
                      ]
                    }
                  }]
                }
              ]
            }' > test-collection.json
      
      - run:
          name: Create Environment
          command: |
            echo '{"values": [{"key": "api_key_value", "value": "'${CIRCLECI_API_TOKEN}'"}]}' > env.json
      
      - newman/newman-run:
          collection: test-collection.json
          environment: env.json

workflows:
  test-api:
    jobs:
      - test-circleci-api:
          context: api-testing-demo